# Generated by Django 4.1 on 2022-08-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdb',
            old_name='Author',
            new_name='author',
        ),
    ]
